# Methods

<!-- KH: Within the methods, suggestion consider adding sub-headings to the methods for each study for 'Data Collection' and 'Analysis'-->

##  Experimental Study 2016

<!-- New header ?: 
### Data Collection 
-->

Sablefish were randomly selected for sampling during the 2016 biennial DFO Groundfish Synoptic Bottom Trawl surveys, following a length stratified protocol. A tally <!--KH: use 'total' instead of 'tally' ?--> of 212 fish were sampled on the West Coast Vancouver Island survey [@Williams2018] and 219 fish were sampled<!--KH: suggestion to delete text 'were sampled'--> on the West Coast Haida Gwaii survey [@Nottingham2018]. In addition, seven small sablefish were collected during the 2016 salmon survey (put reference here) (Figure \@ref(fig:figure1)). <!--KH: At present, the salmon survey is in Figure 1 legend, but no pink points on map. Is the plan still to add that to the map?  Or, you could put a description here of what parts of the coast the salmon survey sampled? -->

For each selected fish, fork length, round weight, sex and maturity were recorded at sea. The heads were removed, labelled <!--KH: labelled with a unique ID?-->and frozen.  On shore, the cranial dimensions of upper jaw (L~UJ~), eye diameter (L~ED~), interorbital distance ( L~ID~), snout length (L~SL~), post orbital to preoperculum distance (L~PP~) and post orbital head length (L~PO~) were measured using Mitutoyo Absolute® 500-762-20 coolant proof digimatic calipers (Table \@ref(tab:table1), Appendix \@ref(app:first-appendix)).  Sagittal otoliths were collected for future ageing.  <!--KH: Suggestion to move the following sentence to a seperate 'Analysis' section: Fork lengths (L~FL~) were estimated by a simple linear regression model, using the cranial measurements as a predictor variables.-->  

At the time of sampling, each cranial dimension was evaluated by experienced samplers <!--KH: how many samplers? Was there repeat measurements at this stage? Or, was is one sampler per fish with different samplers doing different fish -->on a five point rating scale in terms of two distinct criteria: 1. ease of use and 2. repeatability. The ease of use metric focused on three key attributes of the measurement learn-ability (task understanding), efficiency (task-completion time) and degree of difficulty (task performance ease).  The repeatability metric focused on ranking each measurement under repeated caliper placement, taking into consideration the soft and hard head tissues <!--KH: What does 'taking into consideration hard and soft tissues mean? -->. 
<!--KH: would help to standardize terms criteria, attribute, and metric above. -->


<!-- KH: Suggested alternative version of above paragraph:

As part of the sampling protocol, samplers scored each of the six cranial dimensions on two different attributes: 1. ease of use and 2. repeatability.  A five-point scale was used to score each attribute. When scoring 'ease of use', samplers were asked to consider learn-ability (i.e., how easy was it to understand the task), efficiencieny (i.e., task completion time), and degree of difficulty (i.e., ease of performing the task).  When scoring 'repeatability', samplers were asked to take repeated measurements of each cranial dimension and assign a score based on the consistency in each measurement under repeated caliper placement.

-->


Operculum clips (DNA) were collected from the first 137 fish measured (79 male and 58 female <!--KH; Are these numbers based on the sex assignments of the samplers? Or, are these DNA results? -->) and forwarded to the Molecular Genetics Laboratory (MGL) for analysis and gender test development.


### Molecular Genetics Laboratory (MGL) genetic sex-determination

<!--KH: Is it possible to add a bit more context into this section?  i.e., molecular genetic analyses were used to determine sex for 137 samples collected during the Experimental Study.  DNA-based sex assignments were then compared with the sex assigned by samplers through their visual inspection of the gonads to determine the  accuracy of science staff at identifying Sablefish sex.-->

DNA multiplex polymerase chain reactions (PCRs) were conducted using fluorescently labelled forward primers.	X-insert and Y-insert specific primers developed by @Rondeau2013 were used, but the X-insert forward and Y-nested reverse were redesigned to produce slightly smaller PCR products (Table \@ref(tab:table2)).   Sex specific alleles were size fractionated in an ABI 3730 capillary DNA analyzer and were scored with ABI GeneMapper using an internal lane sizing standard. 



<!-- New header ?: 
### Data Analysis
KH: Moved the follwing sentence from above here:
Fork lengths (L~FL~) were estimated by a simple linear regression model, using the cranial measurements as a predictor variables.

## KH: Also, is it also possible to add a couple more sentences to this analysis section?  This could include re-iterating why the regression was done (i.e., to determine how well each of the six candidate cranial measurements could predict fork length).  You could also include a bit more info on linear regressions (i.e., package in R that was used, how you assessed model fit)

-->



## Pilot study 2017 
<!-- KH: Change this header to 'Fishery Pilot Study 2017'? 
-- I like the addition of the word 'Fishery' because it helps identify that commercial fishers were part of this study. Thoughts??  -->

<!-- New header ?: 
### Data Collection
-->

In 2017, a pilot study was conducted with the commercial sector returning sablefish head-only samples.  A total of 360 heads were collected from J-cut sablefish on a limited-entry fishery trip to the Cobb and Eickelberg seamounts (Figure \@ref(fig:figure1)).  Each operculum was marked by commercial fishers with either one knife cut (male) or two knife cuts (female) (Appendix \@ref(app:second-appendix)).  

Scientific sampling occurred on shore, with the first 99 heads of the pilot study measured by three samplers for L~ID~, L~SL~, L~UJ~ and L~PP~.  <!--KH: Why were just these four used instead of original 6? Was is based on preliminary results from the Experimental Study? i.e., there was an early decision that these 4 were most promising? -->

<!--KH: could also add 'Three different samplers were used at this stage of the Fishery Pilot Study to better quantify the repeatability cranial head measurements -->



<!-- New header ?: 
### Data Analysis
-->


Given that three highly experienced technicians were used to conduct the same measurements of the each head morphometric, the Index of Average Error (IAE) (Beamish 1981 <!--KH: note that Beamish 1981 is not in refs. Can you please send it to me so I can have a quick look at it to make sure I'm understanding correctly?  Is it this paper: https://cdnsciencepub.com/doi/pdf/10.1139/f81-132?-->) was calculated to find the most consistent cranial measurement. It is defined as:
$$
IAE=\frac{1}{N}\sum_{j = 1}^{N}\left[\frac{1}{R}\sum_{i = 1}^{R}\frac{ - X_j|}{X_j}\right]
$$
<!--KH: what is the addition | symbol after X_j in the numerator mean?? -->

where N is the number of sablefish measured for each cranial measurement, R is the number of times each cranial measurement was taken, $X_{ij}$ is the average cranial length for the jth sablefish, and $X_{ij}$ is the ith cranial measurement of the jth sablefish.

<!--KH: Note that in equation, you just use X_i, but in text, you denote variables as X_i,j.  Is the neccesary correction to change the equation so that X_j becomes X_{i,j}??  In this case, I think you would describe variables in text as "$X_{ij}$ is the cranial length measurement of the jth sablefish taken by the ith sampler"  Is this right?-->


<!-- KH: It would also be helpful to include a brief description of what IAE represents (is it a measure of precision??), which I can help with if you like-->

Fin clips (95 of 99) were forwarded to the molecular genetics lab for an audit of fisher sex determination. 
