# Results

```{r yisFORKLENGTH}

    lmp <- function (modelobject) {                    #  p value function
           if (class(modelobject) != "lm") stop("Not an object of class 'lm' ")
                 f <- summary(modelobject)$fstatistic
                 p <- pf(f[1],f[2],f[3],lower.tail=F)
                 attributes(p) <- NULL
                 return(p)
    }

    lmslp <- function (modelobject) {                    #  slope (m) value function
             if (class(modelobject) != "lm") stop("Not an object of class 'lm' ")
                 slp <- signif(modelobject$coef[[2]], 5)
                 return(slp)
    }
    
    lmR <- function (modelobject) {                    #  r2 value function
             if (class(modelobject) != "lm") stop("Not an object of class 'lm' ")
                 r2 =  format(summary(modelobject)$r.squared,  digits = 3)
                 return(r2)
    }
    
    
    # y = Fork_Length, response variable
    options("scipen"=100, "digits"=3)
    

```    
   
#  Sample collection

The endemic and endangered status makes, P. denisonii an important freshwater species of study and the biometrics information is useful for more effective management of in-situ conservation. A total of 306 specimens comprising 111 males, 97 females and 98 indeterminate were used for the study. The smallest length of captured fish was 3.30 cm and highest was 14.00 cm in TL (Table 1).

A total of 438 specimens comprising xx males and xx females were collected for six head measurements (UJ,ED,IO,SL, PP, PH),  fork length, round weight, otoliths and DNA. 
Post orbital head length (Posterior inner edge of orbit to dorsal insertion of opercle) was also measured, but this was abandoned after 130 measurements, to save time, and because it was not possible to measure this on a number of the heads for a variety of reasons (opercula had been cut off from some heads, it was awkward to take longer measurements using the electronic calipers, and the end points of the measurement were difficult to define.  


The mean values of the predictor and  response variables  (Table \@ref(tab:table2)).  

Given the ease of measurement, we suggest that Interorbital distance be used to predict sablefish fork lengths and weights (Table \@ref(tab:table3)). 

We found evidence of relationships between upper jaw length and fork length (p = `r lmp(lm(Fork_Length ~ Upper_jaw_length, data=hdUj))`) ; eye diameter and fork length (p = `r lmp(lm(Fork_Length ~ Eye_Diameter, data=hdEd))`); interorbital distance and fork length (p = `r lmp(lm(Fork_Length ~ InterOrbital_Distance, data=hdId))` ); upper snout length and fork length (p = `r lmp(lm(Fork_Length ~ Snout_length, data=hdSl))`); postorbital to preoperculum length and fork length (p = `r lmp(lm(Fork_Length ~ Postorbital_Preoperculum, data=hdPop))`); and postorbital head length and fork length (p = `r lmp(lm(Fork_Length ~ Post_orbital_Head_length, data=hdPo))`).

The estimated slope is `r lmslp(lm(Fork_Length ~ Upper_jaw_length, data=hdUj))` (SE `r coef(summary(lm(Fork_Length ~ Upper_jaw_length, data=hdUj)))[,"Std. Error"][2]`) units of fork length per unit of upper jaw length; the estimated slope is `r lmslp(lm(Fork_Length ~ Eye_Diameter, data=hdEd))` (SE `r  coef(summary(lm(Fork_Length ~ Eye_Diameter, data=hdEd)))[, "Std. Error"][2]`) units of fork length per unit of eye diameter; the estimated slope is `r lmslp(lm(Fork_Length ~ InterOrbital_Distance, data=hdId))` (SE `r coef(summary(lm(Fork_Length ~ InterOrbital_Distance, data=hdId)))[, "Std. Error"][2]`) units of fork length per unit of interorbital distance; the estimated slope is `r lmslp(lm(Fork_Length ~ Snout_length, data=hdSl))` (SE `r coef(summary(lm(Fork_Length ~ Snout_length, data=hdSl)))[, "Std. Error"][2]` units of fork length per unit of snout length; the estimated slope is `r lmslp(lm(Fork_Length ~ Postorbital_Preoperculum, data=hdPop))` (SE `r coef(summary(lm(Fork_Length ~ Postorbital_Preoperculum, data=hdPop)))[, "Std. Error"][2]`) units of fork length per unit of postorbital to preoperculum length; and the estimated slope is `r lmslp(lm(Fork_Length ~ Post_orbital_Head_length, data=hdPo))` (SE `r coef(summary(lm(Fork_Length ~ Post_orbital_Head_length, data=hdPo)))[, "Std. Error"][2]`) units of fork length per unit of postorbital head length.

#  Pilot Collection of Sablefish Heads as a Biological Sample

Heads were received by DFO in good condition (intact and not deformed), segregated by set, for measuring and otolith extraction.  Operculum cuts worked well to indicate sex

#  Repeatability of measurements between technicians

\clearpage