#Tables


(ref:Table1Caption) Definition of head dimensions measured and instructions for positioning the calipers.

```{r table1,  echo=FALSE}
  library(kableExtra)

  options(knitr.kable.NA = '')
  table1   <-  read.csv("c:/github/headresults/storage/table1.csv",header=T)

   kableExtra::kable(table1,
                    booktabs = TRUE,linesep = "",
                    format = "latex",  caption = "(ref:Table1Caption)") %>%
                    row_spec(2,  hline_after = T) %>%
  kableExtra::kable_styling(font_size = 8, position = "left",latex_options = "hold_position")
  
    
```

(ref:Table2Caption) Ease of Use and Repeatability Considerations for each Measurement.

```{r table2,  echo=FALSE}
  library(kableExtra)

  options(knitr.kable.NA = '')
  table1   <-  read.csv("c:/github/headresults/storage/table2.csv",header=T)

   kableExtra::kable(table1,
                    booktabs = TRUE,linesep = "",
                    format = "latex",  caption = "(ref:Table2Caption)") %>%
                    row_spec(2,  hline_after = T) %>%
  kableExtra::kable_styling(font_size = 8, position = "left",latex_options = "hold_position")
  
    
```