# Tables
(ref:Table1Caption) Definition of head dimensions measured and instructions for positioning the calipers.
\ \
\ \
```{r table1, echo=FALSE}
     options(knitr.kable.NA = '')

     table1   <-  read.csv("c:/github/sablehead/standalone/table1.csv", header=T)
     kableExtra::kable(table1,
                     booktabs = TRUE,linesep = "",
                     format = "latex",  caption = "(ref:Table1Caption)") %>%
                     row_spec(1,  hline_after = T) %>%
                     row_spec(2,  hline_after = T) %>%
                     row_spec(3,  hline_after = T) %>%
                     row_spec(4,  hline_after = T) %>%
                     row_spec(5,  hline_after = T) %>%

     
     kableExtra::kable_styling(font_size = 8) %>%
                      column_spec(1, width  = "2.2cm") %>%
                      column_spec(2, width  = "2.7cm") %>%
                      column_spec(3, width  = "4.7cm") 

```
(ref:Table2Caption) Table of sample size, mean and standard deviation for predictor and response variables.

```{r table2, echo=FALSE}

    hd                     <-  hdUj                     # table of sample size, mean and sd for variables
    fl.nme                 <-  "Fork length"
    n                      <-  length(hd$SPECIMEN_ID)                   
    mn                     <-  round(mean(hd$Upper_jaw_length),3)
    mnfl                   <-  round(mean(hd$Fork_Length),3)
    std                    <-  round(sd(hd$Upper_jaw_length),3)
    stdfl                  <-  round(sd(hd$Fork_Length),3)
    
    head.data <-  data.frame(measurement="Upper jaw length",n,mn, std, fl.nme, mnfl, stdfl)
    head.data$measurement  <- as.character(head.data$measurement)
    #typeof(head.data$measurement)
 
    hd                     <-  hdEd                     # table of sample size, mean and sd for variables
    n                      <-  length(hd$SPECIMEN_ID)                   
    mn                     <-  round(mean(hd$Eye_Diameter),3)
    mnfl                   <-  round(mean(hd$Fork_Length),3)
    std                    <-  round(sd(hd$Eye_Diameter),3)
    stdfl                  <-  round(sd(hd$Fork_Length),3)
  
    head.data[2,] <- c("Eye diameter",n,mn, std, fl.nme, mnfl, stdfl)
    
    hd                     <-  hdId                     # table of sample size, mean and sd for variables
    n                      <-  length(hd$SPECIMEN_ID)                   
    mn                     <-  round(mean(hd$InterOrbital_Distance),3)
    mnfl                   <-  round(mean(hd$Fork_Length),3)
    std                    <-  round(sd(hd$InterOrbital_Distance),3)
    stdfl                  <-  round(sd(hd$Fork_Length),3)
  
    head.data[3,] <- c("InterOrbital distance",n, mn, std, fl.nme, mnfl, stdfl)
    
    hd                     <-  hdSl                     # table of sample size, mean and sd for variables
    n                      <-  length(hd$SPECIMEN_ID)                   
    mn                     <-  round(mean(hd$Snout_length),3)
    mnfl                   <-  round(mean(hd$Fork_Length),3)
    std                    <-  round(sd(hd$Snout_length),3)
    stdfl                  <-  round(sd(hd$Fork_Length),3)
  
    head.data[4,] <-c("Snout length",n, mn, std, fl.nme, mnfl, stdfl)
    
    hd                     <-  hdPop                     # table of sample size, mean and sd for variables
    n                      <-  length(hd$SPECIMEN_ID)                   
    mn                     <-  round(mean(hd$Postorbital_Preoperculum),3)
    mnfl                   <-  round(mean(hd$Fork_Length),3)
    std                    <-  round(sd(hd$Postorbital_Preoperculum),3)
    stdfl                  <-  round(sd(hd$Fork_Length),3)
  
    head.data[5,] <- c("Post orbital to preoperculum length",n,mn, std, fl.nme, mnfl, stdfl)
    
    hd                     <-  hdPo                     # table of sample size, mean and sd for variables
    n                      <-  length(hd$SPECIMEN_ID)                   
    mn                     <-  round(mean(hd$Post_orbital_Head_length),3)
    mnfl                   <-  round(mean(hd$Fork_Length),3)
    std                    <-  round(sd(hd$Post_orbital_Head_length),3)
    stdfl                  <-  round(sd(hd$Fork_Length),3)
  
    head.data[6,]     <- c("Post orbital head length",n,mn, std, fl.nme, mnfl, stdfl)
    names(head.data)  <- c("Predictor variable", "n", "mean", "sd", "Response variable", "mean", "sd")
    
    kableExtra::kable(head.data,
                     booktabs = TRUE,linesep = "",
                     format = "latex",  caption = "(ref:Table2Caption)") %>%
     
    kableExtra::kable_styling(font_size = 8, position = "center") %>%
                      column_spec(1, width  = "3.7cm") %>%
                      column_spec(2, width  = "0.6cm") %>%
                      column_spec(3, width  = "0.6cm") %>%
                      column_spec(4, width  = "0.6cm") %>%
                      column_spec(5, width  = "2.1cm") %>%
                      column_spec(6, width  = "0.8cm") %>%
                      column_spec(7, width  = "0.6cm")
```   
   

(ref:Table3Caption) Ease of use and repeatability considerations for each measurement.

```{r table3, echo=FALSE}
     options(knitr.kable.NA = '')

     table2      <-  read.csv("c:/github/sablehead/standalone/table2.csv", header=T)
     table2[1,3] <-  lmR(lm(Fork_Length ~ Upper_jaw_length, data=hdUj))
     table2[2,3] <-  lmR(lm(Fork_Length ~ Eye_Diameter, data=hdEd))
     table2[3,3] <-  lmR(lm(Fork_Length ~ InterOrbital_Distance, data=hdId))
     table2[4,3] <-  lmR(lm(Fork_Length ~ Snout_length, data=hdSl))
     table2[5,3] <-  lmR(lm(Fork_Length ~ Postorbital_Preoperculum, data=hdPop))
     table2[6,3] <-  lmR(lm(Fork_Length ~ Post_orbital_Head_length, data=hdPo))
     
     kableExtra::kable(table2,
                     booktabs = TRUE,linesep = "",
                     format = "latex",  caption = "(ref:Table3Caption)") %>%
                     row_spec(1,  hline_after = T) %>%
                     row_spec(2,  hline_after = T) %>%
                     row_spec(3,  hline_after = T) %>%
                     row_spec(4,  hline_after = T) %>%
                     row_spec(5,  hline_after = T) %>%
     
     kableExtra::kable_styling(font_size = 8, position = "center") %>%
                      column_spec(1, width  = "1.6cm") %>%
                      column_spec(2, width  = "0.6cm") %>%
                      column_spec(3, width  = "0.6cm") %>%
                      column_spec(4, width  = "1.7cm") %>%
                      column_spec(5, width  = "1.2cm") %>%
                      column_spec(6, width  = "3.7cm")

```


\clearpage